### ISSUE TITLE
Code assumes malloc returns zeroed memory. That is false assumption.

### ISSUE THREAD

**Issue by funny-falcon** [rochus-keller/CspChan#2]

**Comment by rochus-keller** [comment]
I'm not aware of any place in the code where this assumption is made. Can you be more specific please?

**Comment by funny-falcon** [comment]
Assumption is in union of [this line](https://github.com/rochus-keller/CspChan/blob/6b04b8317aed5aa886fe8a6486c5f40bc426884f/CspChan.c#L143) and of absence of lines after [this one](https://github.com/rochus-keller/CspChan/blob/6b04b8317aed5aa886fe8a6486c5f40bc426884f/CspChan.c#L153).

**Comment by rochus-keller** [comment]
Ooops, I indeed forgot the memset on line 153, thanks for pointing out! Got unnoticed because all tests are < SignalsCount. Fixed (https://github.com/rochus-keller/CspChan/commit/6867c1a28e1443633bb99b65652bf58f033f5bb9).

**Comment by rochus-keller** [comment]
Can we close this?
